USE IntegracaoCielo
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Vinícius Batista Barreira
-- Create date: 15/12/2015
-- =============================================
CREATE PROCEDURE SPU_INSERE_ARQUIVO_CIELO_DETALHES_CV 
@ID UNIQUEIDENTIFIER
,@TIPODEREGISTRO VARCHAR(1)
,@ESTABELECIMENTOSUBMISSOR VARCHAR(10)
,@NUMERODORO VARCHAR(7)
,@NUMERODOCARTAOTRUNCADO VARCHAR(19)
,@DATADAVENDAAJUSTE VARCHAR(8)
,@SINALDOVALORDACOMPRAOUVALORDAPARCELA VARCHAR(1)
,@VALORDACOMPRAOUVALORDAPARCELA VARCHAR(13)
,@PARCELA VARCHAR(2)
,@TOTALDEPARCELAS VARCHAR(2)
,@MOTIVODAREJEICAO VARCHAR(3)
,@CODIGODEAUTORIZACAO VARCHAR(6)
,@TID VARCHAR(20)
,@NSUDOC VARCHAR(6)
,@VALORCOMPLEMENTAR VARCHAR(13)
,@DIGCARTAO VARCHAR(2)
,@VALORTOTALDAVENDANOCASODEPARCELADOLOJA VARCHAR(13)
,@VALORDAPROXIMAPARCELA VARCHAR(13)
,@NUMERODANOTAFISCAL VARCHAR(9)
,@INDICADORDECARTAOEMITIDONOEXTERIOR VARCHAR(4)
,@NUMEROLOGICODOTERMINAL VARCHAR(8)
,@IDENTIFICADORDETAXADEEMBARQUEOUVALORDEENTRADA VARCHAR(2)
,@REFERENCIACODIGODOPEDIDO VARCHAR(20)
,@HORADATRANSACAO VARCHAR(6)
,@NUMEROUNICODATRANSACAO VARCHAR(29)
,@INDICADORCIELOPROMO VARCHAR(1)
,@USOCIELO VARCHAR(32)

AS
BEGIN
	
	SET NOCOUNT ON;

	INSERT INTO 
		[dbo].[ArquivoCieloDetalhesCV] 
			([Id]
			,[TipoDeRegistro]
			,[EstabelecimentoSubmissor]
			,[NumeroDoRO]
			,[NumeroDoCartaoTruncado]
			,[DataDaVendaAjuste]
			,[SinalDoValorDaCompraOuValorDaParcela]
			,[ValorDaCompraOuValorDaParcela]
			,[Parcela]
			,[TotalDeParcelas]
			,[MotivoDaRejeicao]
			,[CodigoDeAutorizacao]
			,[TID]
			,[NSUDOC]
			,[ValorComplementar]
			,[DigCartao]
			,[ValorTotalDaVendaNoCasoDeParceladoLoja]
			,[ValorDaProximaParcela]
			,[NumeroDaNotaFiscal]
			,[IndicadorDeCartaoEmitidoNoExterior]
			,[NumeroLogicoDoTerminal]
			,[IdentificadorDeTaxaDeEmbarqueOuValorDeEntrada]
			,[ReferenciaCodigoDoPedido]
			,[HoraDaTransacao]
			,[NumeroUnicoDaTransacao]
			,[IndicadorCieloPromo]
			,[UsoCielo]) 
		VALUES 
			(@ID
			,@TIPODEREGISTRO
			,@ESTABELECIMENTOSUBMISSOR
			,@NUMERODORO
			,@NUMERODOCARTAOTRUNCADO
			,@DATADAVENDAAJUSTE
			,@SINALDOVALORDACOMPRAOUVALORDAPARCELA
			,@VALORDACOMPRAOUVALORDAPARCELA
			,@PARCELA
			,@TOTALDEPARCELAS
			,@MOTIVODAREJEICAO
			,@CODIGODEAUTORIZACAO
			,@TID
			,@NSUDOC
			,@VALORCOMPLEMENTAR
			,@DIGCARTAO
			,@VALORTOTALDAVENDANOCASODEPARCELADOLOJA
			,@VALORDAPROXIMAPARCELA
			,@NUMERODANOTAFISCAL
			,@INDICADORDECARTAOEMITIDONOEXTERIOR
			,@NUMEROLOGICODOTERMINAL
			,@IDENTIFICADORDETAXADEEMBARQUEOUVALORDEENTRADA
			,@REFERENCIACODIGODOPEDIDO
			,@HORADATRANSACAO
			,@NUMEROUNICODATRANSACAO
			,@INDICADORCIELOPROMO
			,@USOCIELO)
  
END
GO
