USE IntegracaoCielo
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Vinícius Batista Barreira
-- Create date: 15/12/2015
-- =============================================
CREATE PROCEDURE SPU_INSERE_ARQUIVO_CIELO_DETALHES
 @ID UNIQUEIDENTIFIER
,@TIPODEREGISTRO VARCHAR(1)
,@ESTABELECIMENTOSUBMISSOR VARCHAR(10)
,@NUMERODORO VARCHAR(7)
,@PARCELA VARCHAR(2)
,@FILLER VARCHAR(1)
,@PLANO VARCHAR(2)
,@TIPODETRANSACAO VARCHAR(2)
,@DATADEAPRESENTACAO VARCHAR(6)
,@DATAPREVISTADEPAGAMENTO VARCHAR(6)
,@DATADEENVIOPARAOBANCO VARCHAR(6)
,@SINALVALORBRUTO VARCHAR(1)
,@VALORBRUTO VARCHAR(13)
,@SINALDACOMISSAO VARCHAR(1)
,@VALORDACOMISSAO VARCHAR(13)
,@SINALDOVALORREJEITADO VARCHAR(1)
,@VALORREJEITADO VARCHAR(13)
,@SINALDOVALORLIQUIDO VARCHAR(1)
,@VALORLIQUIDO VARCHAR(13)
,@BANCO VARCHAR(4)
,@AGENCIA VARCHAR(5)
,@CONTACORRENTE VARCHAR(14)
,@STATUSDOPAGAMENTO VARCHAR(2)
,@QUANTIDADEDECVSACEITOS VARCHAR(6)
,@CODIGODOPRODUTODESCONSIDERAR VARCHAR(2)
,@QUANTIDADESDECVSREJEITADOS VARCHAR(6)
,@IDENTIFICADORDEREVENDAACELERACAO VARCHAR(1)
,@DATADACAPTURADETRANSACAO VARCHAR(6)
,@ORIGEMDOAJUSTE VARCHAR(2)
,@VALORCOMPLEMENTAR VARCHAR(13)
,@IDENTIFICADORDEANTECIPACAO VARCHAR(1)
,@NUMERODAOPERACAODEANTECIPACAO VARCHAR(9)
,@SINALDOVALORBRUTOANTECIPADO VARCHAR(1)
,@VALORBRUTOANTECIPADO VARCHAR(13)
,@BANDEIRA VARCHAR(3)
,@NUMEROUNICODORO VARCHAR(22)
,@TAXADECOMISSAO VARCHAR(4)
,@TARIFA VARCHAR(5)
,@TAXADEGARANTIA VARCHAR(4)
,@MEIODECAPTURA VARCHAR(2)
,@NUMEROLOGICODOTERMINAL VARCHAR(8)
,@CODIGODOPRODUTO VARCHAR(3)
,@MATRIZDEPAGAMENTO VARCHAR(10)
,@USOCIELO VARCHAR(5)
	
AS
BEGIN
	
	SET NOCOUNT ON;

	INSERT INTO 
		[dbo].[ArquivoCieloDetalhes] 
			([Id]
			,[TipoDeRegistro]
			,[EstabelecimentoSubmissor]
			,[NumeroDoRO]
			,[Parcela]
			,[Filler]
			,[Plano]
			,[TipoDeTransacao]
			,[DataDeApresentacao]
			,[DataPrevistaDePagamento]
			,[DataDeEnvioParaoBanco]
			,[SinalValorBruto]
			,[ValorBruto]
			,[SinalDaComissao]
			,[ValorDaComissao]
			,[SinalDoValorRejeitado]
			,[ValorRejeitado]
			,[SinalDoValorLiquido]
			,[ValorLiquido]
			,[Banco]
			,[Agencia]
			,[ContaCorrente]
			,[StatusDoPagamento]
			,[QuantidadeDeCVsAceitos]
			,[CodigoDoProdutoDesconsiderar]
			,[QuantidadesDeCVsRejeitados]
			,[IdentificadorDeRevendaAceleracao]
			,[DataDaCapturaDeTransacao]
			,[OrigemDoAjuste]
			,[ValorComplementar]
			,[IdentificadorDeAntecipacao]
			,[NumeroDaOperacaoDeAntecipacao]
			,[SinalDoValorBrutoAntecipado]
			,[ValorBrutoAntecipado]
			,[Bandeira]
			,[NumeroUnicoDoRO]
			,[TaxaDeComissao]
			,[Tarifa]
			,[TaxaDeGarantia]
			,[MeioDeCaptura]
			,[NumeroLogicoDoTerminal]
			,[CodigoDoProduto]
			,[MatrizDePagamento]
			,[UsoCielo]) 
		VALUES 
			(@ID
			,@TIPODEREGISTRO
			,@ESTABELECIMENTOSUBMISSOR
			,@NUMERODORO
			,@PARCELA
			,@FILLER
			,@PLANO
			,@TIPODETRANSACAO
			,@DATADEAPRESENTACAO
			,@DATAPREVISTADEPAGAMENTO
			,@DATADEENVIOPARAOBANCO
			,@SINALVALORBRUTO
			,@VALORBRUTO
			,@SINALDACOMISSAO
			,@VALORDACOMISSAO
			,@SINALDOVALORREJEITADO
			,@VALORREJEITADO
			,@SINALDOVALORLIQUIDO
			,@VALORLIQUIDO
			,@BANCO
			,@AGENCIA
			,@CONTACORRENTE
			,@STATUSDOPAGAMENTO
			,@QUANTIDADEDECVSACEITOS
			,@CODIGODOPRODUTODESCONSIDERAR
			,@QUANTIDADESDECVSREJEITADOS
			,@IDENTIFICADORDEREVENDAACELERACAO
			,@DATADACAPTURADETRANSACAO
			,@ORIGEMDOAJUSTE
			,@VALORCOMPLEMENTAR
			,@IDENTIFICADORDEANTECIPACAO
			,@NUMERODAOPERACAODEANTECIPACAO
			,@SINALDOVALORBRUTOANTECIPADO
			,@VALORBRUTOANTECIPADO
			,@BANDEIRA
			,@NUMEROUNICODORO
			,@TAXADECOMISSAO
			,@TARIFA
			,@TAXADEGARANTIA
			,@MEIODECAPTURA
			,@NUMEROLOGICODOTERMINAL
			,@CODIGODOPRODUTO
			,@MATRIZDEPAGAMENTO
			,@USOCIELO)
  
END
GO
